### ISSUE TITLE
enhancement: Getter for internal value of LocalValue.

### ISSUE THREAD

**Issue by dload0** [henryhchchc/mokapot#12]
I'm sure you're glad to see me again! 😭 I'm still using this library for my obfuscation / virtualization projects - super cool!

As I'm parsing some MokaIR, I come across many `LocalValue` structs from `moka_instruction.rs`. I understand that by formatting it (such in printing etc), it will reveal the internal value stored by the struct `%<value>`. However, I'd much rather be able to access the u16 from within it directly.

What would be your thoughts on how to implement this? Would you be willing to expose it using `pub u16`, or perhaps a getter method in the implementation of the struct?

A simple setter like this could suffice if you didn't want to expose it via field access. 😄 

```rust
impl LocalValue {
    // ...existing.
    
    #[must_use]
    pub fn as_value(&self) -> u16 {
        self.0
    }
}
```

**Comment by henryhchchc** [comment]
I think it would be a good idea to implement `Into<u16>` for it.

**Comment by dload0** [comment]
Implemented `From<LocalValue> for u16` @ https://github.com/henryhchchc/mokapot/pull/13. Is that good? 😄
