### ISSUE TITLE
enhancement: Add PartialEq derive to `Annotation`.

### ISSUE THREAD

**Issue by dload0** [henryhchchc/mokapot#14]
I think it would be useful to have some structs derive PartialEq within the `jvm` API.

One such example that would be handy for me is the  `Annotation` struct, as I need to filter out methods based on whether the method has a specific `runtime_visible_annotations` entry:

```rust
if method.runtime_visible_annotations.contains(
    &Annotation {
        annotation_type: FieldType::Object(
            ClassRef {
                binary_name: "some/package/Name".to_string()
            }
        ),
        element_value_pairs: vec![],
    }
) {
    // Filter...
}
```

I have added the derive in my own fork, but I was wondering if this could be usefully applied to any other structs - and commited in bulk.

**Comment by henryhchchc** [comment]
I agree. I think `Annotation` is not the only structure where `PartialEq` is missing. It would be nice if we could figure out a list of structs that we should add `PartialEq`, and possibly `Eq` and `Hash`.

**Comment by dload0** [comment]
- `Annotation` - and by proxy `ElementValue`.
- `TypeAnnotation` - and by proxy `TargetInfo`, `TypePathElement` & `ElementValue`.

Both of these would make sense, and can be implemented with relative ease.
