### ISSUE TITLE
bug: Incorrect IR emitted in generated MokaIR.

### ISSUE THREAD

**Issue by dload0** [henryhchchc/mokapot#6]
Correct me if I'm completely wrong, but looking at the MokaIR example [here](https://github.com/henryhchchc/mokapot/blob/main/docs/MokaIR.md), around PC #002C:

```rust
%40 = int(0)
nop
nop
nop
if %arg1 >= Phi(%40, %64) goto #0046
...
```

Which is the condition for the `for` loop at L18 in the TestAnalysis.java source [here](https://github.com/henryhchchc/mokapot/blob/main/test_data/mokapot/org/mokapot/test/TestAnalysis.java#L18):

```java
for (int i = 0; i < y; i++) {
  ...
}
```

Will always evaluate to `true` when `%arg1`/`y` is passed a value over 0, jumping to #0046 (which breaks out of the `for` loop).

I am not sure if this is a misunderstanding on my part with the use of Phi; however, looking at this from my perspective, it still looks like the arguments for the conditional have been reversed.

**Comment by henryhchchc** [comment]
Thanks for your interest in this project.

`Phi(%40, %64)` is the $\phi$ function in the [Static single assignment form](https://en.wikipedia.org/wiki/Static_single-assignment_form). In this example, it is not simply *`%40` or `%64`*, but depending on the actual execution. At the first execution of `#002C`, it goes through the path `#0028 -> #0029 -> .. -> #002C` then the value of `Phi(%40, %64)` will be `%40`. At the second execution of `#002C`, it goes through the path `#0040 -> #0043 -> #002A -> #002B -> #002C`, and the value of `Phi(%40, %64)` will be `%64`.
```
#0028: iconst_0         => %40 = int(0)
#0029: istore_3         => nop
#002A: iload_3          => nop
#002B: iload_2          => nop
#002C: if_icmpge        => if %arg1 >= Phi(%40, %64) goto #0046
...
#0040: iinc             => %64 = Phi(%40, %64) + 1
#0043: goto             => goto #002A
```

**Comment by dload0** [comment]
This project is great by the way! I'm using it in two of my own, this is just the first time attempting to use MokaIR. :smile:

So how is the line #002C evaluated at all? Taking the first first execution where `Phi(%40, %64)` is `%40`, collapsing the line to:

```rust
if %arg1 >= %40 goto #0046
```

And since `%40` is set to `int(0)`, surely the expression is `true` (assuming `%arg1`/`y` is above 0)? 

```rust
if <some value above 0> >= 0 goto #0046
```

And then, as you say during the second execution, the value of `Phi(%40, %64)` is `%64`, collapsing the line to:

```rust
if %arg1 >= %64 goto #0046
```

Which is declared at #0040 (which I assume to be 1, since first execution will use `%40` + 1 - therefore 0 + 1), but then will still break out of the block if `%arg1`/`y` is above 1.

So in my head, passing say 5 to `%arg1`/`y`, will break out of the loop on first evaluation of #002C, since Phi would collapse to `%40`, but say even if the block is executed, and then `%64` is decalred, the next evaluation of #002C as you say will compare 5 against 1, which will break out again?

Forgive me if I'm wrong again haha, I just can't figure out in this case how that line ever enters the loop block. :confused:

**Comment by henryhchchc** [comment]
You are correct. I found that it is a bug in my implementation when converting the stack based JVM byte code to register based IR. The bug will make all the binary operations have their operands swapped.

I will fix it soon. Thanks for bringing this into my attention.
